# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 17:12
from __future__ import unicode_literals

from django.db import migrations
import ecommerce.extensions.offer.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0017_condition_journal_bundle_uuid'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalBundleCondition',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=(ecommerce.extensions.offer.mixins.SingleItemConsumptionConditionMixin, 'offer.condition'),
        ),
    ]
