# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-16 03:34


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_auto_20161027_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='basket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.Basket'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order'),
        ),
    ]
