# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-22 12:20
from __future__ import unicode_literals

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0002_auto_20151214_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrefund',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrefund',
            name='order',
        ),
        migrations.RemoveField(
            model_name='historicalrefund',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalrefundline',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrefundline',
            name='order_line',
        ),
        migrations.RemoveField(
            model_name='historicalrefundline',
            name='refund',
        ),
        migrations.AlterField(
            model_name='refund',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='refundline',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='refundline',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.DeleteModel(
            name='HistoricalRefund',
        ),
        migrations.DeleteModel(
            name='HistoricalRefundLine',
        ),
    ]
