# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-19 09:03


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0002_auto_20151214_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrefund',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrefund',
            name='order',
        ),
        migrations.RemoveField(
            model_name='historicalrefund',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalrefundline',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrefundline',
            name='order_line',
        ),
        migrations.RemoveField(
            model_name='historicalrefundline',
            name='refund',
        ),
        migrations.DeleteModel(
            name='HistoricalRefund',
        ),
        migrations.DeleteModel(
            name='HistoricalRefundLine',
        ),
    ]
