# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0004_auto_20180403_1120'),
        ('refund', '0004_auto_20180326_1545'),
    ]

    operations = [
    ]
