# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-16 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20170215_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogue.HistoricalProduct'),
        ),
    ]
