# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-07 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_catalogue_entitlement_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='course',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='product_class',
        ),
        migrations.RemoveField(
            model_name='historicalproductattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='historicalproductattributevalue',
            name='entity_content_type',
        ),
        migrations.RemoveField(
            model_name='historicalproductattributevalue',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproductattributevalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalproductattributevalue',
            name='value_option',
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
        migrations.DeleteModel(
            name='HistoricalProductAttributeValue',
        ),
    ]
