# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-22 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_catalogue_entitlement_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='historicalproductattributevalue',
            name='entity_content_type',
        ),
        migrations.RemoveField(
            model_name='historicalproductattributevalue',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproductattributevalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalproductattributevalue',
            name='value_option',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalProductAttributeValue',
        ),
    ]
