# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-19 09:03


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_donations_from_checkout_tests_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='course',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='product_class',
        ),
        migrations.RemoveField(
            model_name='historicalproductattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='historicalproductattributevalue',
            name='entity_content_type',
        ),
        migrations.RemoveField(
            model_name='historicalproductattributevalue',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproductattributevalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalproductattributevalue',
            name='value_option',
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
        migrations.DeleteModel(
            name='HistoricalProductAttributeValue',
        ),
    ]
