# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-24 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_digital_book_product_class'),
        ('catalogue', '0029_auto_20180119_0903'),
    ]

    operations = [
    ]
