# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_auto_20180124_1131'),
        ('catalogue', '0031_digital_book_product_class'),
    ]

    operations = [
    ]
