# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-10 11:29


from django.db import migrations

from ecommerce.extensions.catalogue.utils import create_subcategories

COUPON_CATEGORY_NAME = 'Coupons'

DEFAULT_CATEGORIES = [
    'Bulk Enrollment - Prepay',
    'Bulk Enrollment - Upon Redemption',
    'Bulk Enrollment - Integration',
]

def create_default_categories(apps, schema_editor):
    """Create default coupon categories."""
    Category = apps.get_model("catalogue", "Category")

    Category.skip_history_when_saving = True
    create_subcategories(Category, COUPON_CATEGORY_NAME, DEFAULT_CATEGORIES)


def remove_default_categories(apps, schema_editor):
    """Remove default coupon categories."""
    Category = apps.get_model("catalogue", "Category")

    Category.skip_history_when_saving = True
    Category.objects.get(name=COUPON_CATEGORY_NAME).get_children().filter(
        name__in=DEFAULT_CATEGORIES
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('catalogue', '0032_journal_product_class'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories)
    ]
