# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-10 11:29


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catalogue', '0032_journal_product_class'),
    ]

    operations = [
    ]
