# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_course_entitlement_idverifyreq_attr'),
        ('catalogue', '0032_merge_20180321_2215'),
    ]

    operations = [
    ]
