# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-22 09:46


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catalogue', '0044_add_enterprisecontractmetadata_product_attribute'),
    ]

    operations = [
    ]
