# Generated by Django 2.2.12 on 2020-07-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0050_add_b2b_affiliate_promotion_coupon_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['value_text', 'attribute', 'product'], name='catalogue_p_value_t_9b30e7_idx'),
        ),
    ]
