# Generated by Django 2.2.14 on 2020-07-27 14:40
from django.core.management import call_command
from django.db import migrations

COUPON_CATEGORY_NAME = 'Coupons'

DEFAULT_CATEGORIES = [
    'Partner No Rev - Prepay',
    'Partner No Rev - Upon Redemption',
    'Bulk Enrollment - Prepay',
    'Bulk Enrollment - Upon Redemption',
    'Bulk Enrollment - Integration',
    'edX Employee Request',
    'Partner No Rev - RAP',
    'Partner No Rev - ORAP',
    'Affiliate Promotion', 'Bulk Enrollment', 'ConnectEd', 'Course Promotion',
    'Customer Service', 'Financial Assistance', 'Geography Promotion',
    'Marketing Partner Promotion', 'Marketing-Other', 'Paid Cohort', 'Other',
    'Retention Promotion', 'Services-Other', 'Support-Other', 'Upsell Promotion',
    'On-Campus Learners',
    'Security Disclosure Reward',
    'B2B Affiliate Promotion',
]


def create_default_categories(apps, schema_editor):
    for category in DEFAULT_CATEGORIES:
        call_command('create_categories_from_breadcrumbs', COUPON_CATEGORY_NAME, category)


def remove_default_categories(apps, schema_editor):
    """Remove default coupon categories."""
    Category = apps.get_model("catalogue", "Category")

    Category.skip_history_when_saving = True
    Category.objects.get(name=COUPON_CATEGORY_NAME).get_children().filter(
        name__in=DEFAULT_CATEGORIES
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0050_add_b2b_affiliate_promotion_coupon_category'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories)
    ]
