# Generated by Django 2.2.26 on 2022-02-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0053_auto_20210922_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackboardLearnerAssessmentDataTransmissionAudittt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blackboard_user_email', models.CharField(max_length=255)),
                ('enterprise_course_enrollment_id', models.PositiveIntegerField(db_index=True)),
                ('enterprise_course_enrollment_name', models.PositiveIntegerField(db_index=True, default=1)),
            ],
        ),
    ]
