# Generated by Django 2.2.26 on 2022-02-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0054_blackboardlearnerassessmentdatatransmissionaudittestingtestingtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackboardlearnerassessmentdatatransmissionaudittestingtestingtest',
            name='enterprise_course_enrollment_name',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
