# Generated by Django 3.2.20 on 2024-01-04 09:32

from django.db import migrations

from ecommerce.core.constants import SEAT_PRODUCT_CLASS_NAME


def create_product_attribute(apps, schema_editor):
    """ Create a product attribute for course seat product class"""
    ProductAttribute = apps.get_model("catalogue", "ProductAttribute")
    ProductClass = apps.get_model("catalogue", "ProductClass")

    for class_iter in (ProductAttribute, ProductClass):
        class_iter.skip_history_when_saving = True

    seat = ProductClass.objects.get(name=SEAT_PRODUCT_CLASS_NAME)

    # Create product attribute for course seat products
    product_attr = ProductAttribute(
        product_class=seat,
        name="variant_id",
        code="variant_id",
        type="text",
        required=False
    )
    product_attr.save()

def remove_product_attribute(apps, schema_editor):
    """ Reverse function. """
    ProductAttribute = apps.get_model("catalogue", "ProductAttribute")
    ProductAttribute.skip_history_when_saving = True
    ProductAttribute.objects.filter(name='variant_id', product_class__name=SEAT_PRODUCT_CLASS_NAME).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0055_sf_opp_line_item_ent_attr'),
    ]

    operations = [
        migrations.RunPython(create_product_attribute, remove_product_attribute),
    ]
