# Generated by Django 3.2.20 on 2024-01-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0056_add_variant_id_seat_product_attr'),
        ('catalogue', '0056_auto_20231108_1355'),
    ]

    operations = [
    ]
