# Generated by Django 3.2.20 on 2024-01-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0057_auto_20231205_1034'),
        ('catalogue', '0057_merge_20240119_1219'),
    ]

    operations = [
    ]
