# Generated by Django 3.2.25 on 2024-05-28 07:54

from django.db import migrations
import oscar.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0057_auto_20231205_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Unique identifier'),
        ),
        migrations.AddField(
            model_name='attributeoptiongroup',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Unique identifier'),
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='code',
            field=oscar.models.fields.NullCharField(db_index=True, max_length=255, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Code'),
        ),
    ]
