# Generated by Django 3.2.20 on 2024-02-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0057_add_app_store_id_product_attr'),
        ('catalogue', '0057_merge_20240119_1219'),
    ]

    operations = [
    ]
