DYNAMIC_DISCOUNT_FLAG = 'offer.dynamic_discount'

# OfferAssignment status constants defined here to avoid circular dependency.
OFFER_ASSIGNMENT_EMAIL_PENDING = 'EMAIL_PENDING'
OFFER_ASSIGNED = 'ASSIGNED'
OFFER_REDEEMED = 'REDEEMED'
OFFER_ASSIGNMENT_EMAIL_BOUNCED = 'EMAIL_BOUNCED'
OFFER_ASSIGNMENT_REVOKED = 'REVOKED'

OFFER_MAX_USES_DEFAULT = 10000

# Coupon code filters
VOUCHER_NOT_ASSIGNED = 'unassigned'
VOUCHER_NOT_REDEEMED = 'unredeemed'
VOUCHER_PARTIAL_REDEEMED = 'partially-redeemed'
VOUCHER_REDEEMED = 'redeemed'

OFFER_ASSIGNMENT_EMAIL_TEMPLATE_FIELD_LIMIT = 50000
OFFER_ASSIGNMENT_EMAIL_SUBJECT_LIMIT = 1000
