CUSTOM_APPLICATOR_LOG_FLAG = 'enable_custom_applicator_logging'
CUSTOM_APPLICATOR_USE_FLAG = 'enable_custom_applicator_use'

# OfferAssignment status constants defined here to avoid circular dependency.
OFFER_ASSIGNMENT_EMAIL_PENDING = 'EMAIL_PENDING'
OFFER_ASSIGNED = 'ASSIGNED'
OFFER_REDEEMED = 'REDEEMED'
OFFER_ASSIGNMENT_EMAIL_BOUNCED = 'EMAIL_BOUNCED'
OFFER_ASSIGNMENT_REVOKED = 'REVOKED'

OFFER_MAX_USES_DEFAULT = 10000
