# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-19 01:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170215_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='require_account_activation',
            field=models.BooleanField(default=True, help_text='Require users to activate their account before allowing them to redeem a coupon.', verbose_name='Require Account Activation'),
        ),
    ]
