# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-31 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170215_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_paypal_webhooks',
            field=models.BooleanField(default=False, verbose_name='Enable PayPal webhook event handler'),
        ),
    ]
