# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-25 17:55


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_siteconfiguration_require_account_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='optimizely_snippet_src',
            field=models.CharField(blank=True, help_text='This script will be loaded on every page.', max_length=255, verbose_name='Optimizely snippet source URL'),
        ),
    ]
