# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20170613_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User locale'),
        ),
    ]
