# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 06:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20170613_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='base_cookie_domain',
            field=models.CharField(blank=True, default=b'', help_text='Base cookie domain used to share cookies across services.', max_length=255, verbose_name='Base Cookie Domain'),
        ),
    ]
