# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 14:14


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_siteconfiguration_base_cookie_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='enable_otto_receipt_page',
        ),
    ]
