# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 17:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_siteconfiguration_enable_otto_receipt_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_embargo_check',
            field=models.BooleanField(default=False, help_text='Enable embargo check at checkout.', verbose_name='Enable embargo check'),
        ),
    ]
