# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_siteconfiguration_enable_embargo_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='course_catalog_api_url',
            field=models.URLField(blank=True, help_text='URL for course catalog API.', verbose_name='Course catalog API URL'),
        ),
    ]
