# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 08:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_siteconfiguration_enable_embargo_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='discovery_api_url',
            field=models.URLField(blank=True, help_text='URL for discovery API.', verbose_name='Discovery API URL'),
        ),
    ]
