# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 02:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_siteconfiguration_discovery_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_apple_pay',
            field=models.BooleanField(default=False, verbose_name='Enable Apple Pay'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='discovery_api_url',
            field=models.URLField(blank=True, verbose_name='Discovery API URL'),
        ),
    ]
