# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 15:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20170716_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='_allowed_segment_events',
            field=models.TextField(default=b'Order Completed, Order Refunded', help_text=b'Comma-separated list of events the service is allowed to transmit to Segment. This is temporary. Do NOT rely on it long-term.', verbose_name=b'Allowed Segment events'),
        ),
    ]
