# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 14:09


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_siteconfiguration__allowed_segment_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='_allowed_segment_events',
        ),
    ]
