# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 10:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_siteconfiguration_enable_partial_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='discovery_api_url',
            field=models.URLField(verbose_name='Discovery API URL'),
        ),
    ]
