# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-10 08:23


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20180313_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
        ),
    ]
