# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20180313_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='journals_api_url',
            field=models.URLField(blank=True, null=True, verbose_name='Journals Service API URL'),
        ),
    ]
