# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-25 14:18
# TODO: journal dependency
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_siteconfiguration_journals_api_url'),
        ('core', '0045_auto_20180510_0823'),
    ]

    operations = [
    ]
