# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-23 17:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_historicalbusinessclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lms_user_id',
            field=models.IntegerField(blank=True, help_text='LMS user id', null=True),
        ),
    ]
