# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-10 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20190626_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='journals_api_url',
        ),
    ]
