# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-20 17:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_siteconfiguration_journals_api_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name=b'email address'),
        ),
    ]
