# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-15 19:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20191115_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='sdn_api_key_v1',
            field=models.CharField(blank=True, max_length=255, verbose_name='US Treasury SDN API v1 key'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='sdn_api_url_v1',
            field=models.CharField(blank=True, max_length=255, verbose_name='US Treasury SDN API v1 URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='sdn_api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='[Deprecated] US Treasury SDN API key'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='sdn_api_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='[Deprecated] US Treasury SDN API URL'),
        ),
    ]
