# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-17 13:12


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20200115_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='sdn_api_key_v1',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='sdn_api_url_v1',
        ),
    ]
