# Generated by Django 2.2.17 on 2021-05-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_braze_switch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='enable_sailthru',
        ),
    ]
