# Generated by Django 2.2.23 on 2021-05-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_siteconfiguration_enable_sailthru'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercefeatureroleassignment',
            name='applies_to_all_contexts',
            field=models.BooleanField(default=False, help_text='If true, indicates that the user is effectively assigned their role for any and all contexts. Defaults to False.'),
        ),
    ]
