# Generated by Django 2.2.24 on 2021-11-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_ecommercefeatureroleassignment_applies_to_all_contexts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='account_microfrontend_url',
        ),
    ]
