# Generated by Django 3.2.12 on 2022-09-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_account_microfrontend_url_field_from_SiteConfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='enable_microfrontend_for_basket_page',
            field=models.BooleanField(blank=True, default=False, help_text='Use the microfrontend implementation of the basket page instead of the server-side template', null=True, verbose_name='Enable Microfrontend for Basket Page'),
        ),
    ]
