# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-22 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170525_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcourse',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='site',
        ),
        migrations.DeleteModel(
            name='HistoricalCourse',
        ),
    ]
