# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-25 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170525_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcourse',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
