# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-18 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20171204_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
