# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-07 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20171204_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcourse',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='site',
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='HistoricalCourse',
        ),
    ]
