# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-19 09:03


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20171204_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcourse',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='site',
        ),
        migrations.DeleteModel(
            name='HistoricalCourse',
        ),
    ]
