# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-27 07:51


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='sites.Site', verbose_name='Site'),
        ),
    ]
