# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 14:31
from __future__ import unicode_literals

from django.db import migrations

import ecommerce.extensions.offer.benefits
import ecommerce.extensions.offer.conditions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0015_auto_20170926_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsoluteDiscountBenefitWithoutRange',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=(ecommerce.extensions.offer.benefits.BenefitWithoutRangeMixin, 'offer.absolutediscountbenefit'),
        ),
        migrations.CreateModel(
            name='EnterpriseCustomerCondition',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=(ecommerce.extensions.offer.conditions.SingleItemConsumptionConditionMixin, 'offer.condition'),
        ),
        migrations.CreateModel(
            name='EnterprisePercentageDiscountBenefit',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=(ecommerce.extensions.offer.benefits.BenefitWithoutRangeMixin, 'offer.percentagediscountbenefit'),
        ),
    ]
