# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-16 03:34


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20160616_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.Basket'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='business_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.BusinessClient'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order'),
        ),
    ]
