# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-07 10:20
from __future__ import unicode_literals

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20170215_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='business_client',
        ),
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='order',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.DeleteModel(
            name='HistoricalInvoice',
        ),
    ]
