# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-19 09:03


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20170215_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='business_client',
        ),
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='order',
        ),
        migrations.DeleteModel(
            name='HistoricalInvoice',
        ),
    ]
