# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 10:57


import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20180119_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(blank=True, choices=[(b'Prepaid', 'Prepaid'), (b'Postpaid', 'Postpaid'), (b'Bulk purchase', 'Bulk purchase'), (b'Not applicable', 'Not applicable')], default=b'Prepaid', max_length=255, null=True),
        ),
    ]
