# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-14 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20180124_1507'),
        ('invoice', '0006_auto_20180228_1057'),
    ]

    operations = [
    ]
