# Generated by Django 2.2.14 on 2020-07-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20191115_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'get_latest_by': 'modified'},
        ),
    ]
