# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 11:12


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_partner_default_site'),
        ('order', '0016_auto_20180119_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
        ),
    ]
