# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-15 21:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_manualenrollmentorderdiscountbenefit_manualenrollmentorderdiscountcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='shipping_code',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
