# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-05 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20191115_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalline',
            name='effective_discount_percentage',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='historicalline',
            name='enterprise_customer_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='effective_discount_percentage',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='enterprise_customer_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
