# Generated by Django 3.2.20 on 2023-11-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20210922_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdiscount',
            options={'ordering': ['pk'], 'verbose_name': 'Order Discount', 'verbose_name_plural': 'Order Discounts'},
        ),
        migrations.AlterModelOptions(
            name='ordernote',
            options={'ordering': ['-date_updated'], 'verbose_name': 'Order Note', 'verbose_name_plural': 'Order Notes'},
        ),
        migrations.RemoveField(
            model_name='historicalline',
            name='est_dispatch_date',
        ),
        migrations.RemoveField(
            model_name='historicalline',
            name='unit_cost_price',
        ),
        migrations.RemoveField(
            model_name='historicalline',
            name='unit_retail_price',
        ),
        migrations.RemoveField(
            model_name='line',
            name='est_dispatch_date',
        ),
        migrations.RemoveField(
            model_name='line',
            name='unit_cost_price',
        ),
        migrations.RemoveField(
            model_name='line',
            name='unit_retail_price',
        ),
    ]
