# Generated by Django 3.2.20 on 2023-08-24 10:28

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20210922_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdiscount',
            options={'ordering': ['pk'], 'verbose_name': 'Order Discount', 'verbose_name_plural': 'Order Discounts'},
        ),
        migrations.AlterModelOptions(
            name='ordernote',
            options={'ordering': ['-date_updated'], 'verbose_name': 'Order Note', 'verbose_name_plural': 'Order Notes'},
        ),
        migrations.RemoveField(
            model_name='historicalline',
            name='est_dispatch_date',
        ),
        migrations.RemoveField(
            model_name='historicalline',
            name='unit_cost_price',
        ),
        migrations.RemoveField(
            model_name='historicalline',
            name='unit_retail_price',
        ),
        migrations.RemoveField(
            model_name='line',
            name='est_dispatch_date',
        ),
        migrations.RemoveField(
            model_name='line',
            name='unit_cost_price',
        ),
        migrations.RemoveField(
            model_name='line',
            name='unit_retail_price',
        ),
        migrations.AlterField(
            model_name='lineattribute',
            name='value',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Value'),
        ),
    ]
