# Generated by Django 3.2.22 on 2023-12-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_alter_lineattribute_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surcharge',
            options={'ordering': ['pk'], 'verbose_name': 'Surcharge', 'verbose_name_plural': 'Surcharges'},
        ),
        migrations.AddField(
            model_name='historicalline',
            name='tax_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='VAT rate code'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_tax_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Shipping VAT rate code'),
        ),
        migrations.AddField(
            model_name='line',
            name='tax_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='VAT rate code'),
        ),
        migrations.AddField(
            model_name='lineprice',
            name='tax_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='VAT rate code'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_tax_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Shipping VAT rate code'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='tax_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='VAT rate code'),
        ),
    ]
