# Generated by Django 3.2.25 on 2024-05-28 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_alter_lineattribute_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surcharge',
            options={'ordering': ['pk'], 'verbose_name': 'Surcharge', 'verbose_name_plural': 'Surcharges'},
        ),
        migrations.AddField(
            model_name='historicalline',
            name='tax_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='VAT rate code'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_tax_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Shipping VAT rate code'),
        ),
        migrations.AddField(
            model_name='line',
            name='tax_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='VAT rate code'),
        ),
        migrations.AddField(
            model_name='lineprice',
            name='tax_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='VAT rate code'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_tax_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Shipping VAT rate code'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='tax_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='VAT rate code'),
        ),
        migrations.CreateModel(
            name='OrderLineDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_incl_tax', models.BooleanField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Line discount (excl. tax)')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='order.line', verbose_name='Line')),
                ('order_discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_lines', to='order.orderdiscount', verbose_name='Order discount')),
            ],
            options={
                'verbose_name': 'Order line discount',
                'verbose_name_plural': 'Order line discounts',
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
