# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-24 11:31


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0004_auto_20160517_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voucherapplication',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
