# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 10:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0005_auto_20180124_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='usage',
            field=models.CharField(choices=[(b'Single use', 'Can be used once by one customer'), (b'Multi-use', 'Can be used multiple times by multiple customers'), (b'Once per customer', 'Can only be used once per customer'), (b'Multi-use-per-Customer', 'Can be used multiple times by one customer')], default=b'Multi-use', max_length=128, verbose_name='Usage'),
        ),
    ]
