# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-15 21:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0007_auto_20190913_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='usage',
            field=models.CharField(choices=[('Single use', 'Can be used once by one customer'), ('Multi-use', 'Can be used multiple times by multiple customers'), ('Once per customer', 'Can only be used once per customer'), ('Multi-use-per-Customer', 'Can be used multiple times by one customer')], default='Multi-use', max_length=128, verbose_name='Usage'),
        ),
    ]
