# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-13 04:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20191115_2151'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voucher', '0009_historicalvoucherapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('coupon_code', models.CharField(db_index=True, max_length=128)),
                ('learner_enterprise_uuid', models.UUIDField()),
                ('learner_enterprise_name', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
            },
        ),
    ]
