# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-05 14:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0009_historicalvoucherapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='end_datetime',
            field=models.DateTimeField(db_index=True, verbose_name='End datetime'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, verbose_name='Start datetime'),
        ),
    ]
