# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-13 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0010_coupontrace'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupontrace',
            name='metadata',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='coupontrace',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='coupontrace',
            name='learner_enterprise_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coupontrace',
            name='learner_enterprise_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
