# Generated by Django 2.2.15 on 2020-09-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0011_auto_20200403_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_public',
            field=models.BooleanField(blank=True, default=False, help_text='Should this code batch be public or private for assignment.', verbose_name='Is Public Code Batch'),
        ),
    ]
