class CertificateType:
    CREDIT = 'credit'
    VERIFIED = 'verified'
    HONOR = 'honor'
    AUDIT = 'audit'
    PROFESSIONAL = 'professional'
    NO_ID_PROFESSIONAL = 'no-id-professional'
    MASTERS = 'masters'
    EXECUTIVE_EDUCATION = 'executive-education'
    UNPAID_EXECUTIVE_EDUCATION = 'unpaid-executive-education'
    PAID_EXECUTIVE_EDUCATION = 'paid-executive-education'
    UNPAID_BOOTCAMP = 'unpaid-bootcamp'
    PAID_BOOTCAMP = 'paid-bootcamp'
