# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-27 14:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20170215_2234'),
        ('payment', '0015_auto_20170215_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdncheckfailure',
            name='address',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='sdncheckfailure',
            name='products',
            field=models.ManyToManyField(related_name='sdn_failures', to='catalogue.Product'),
        ),
    ]
