# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-28 14:45


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20170227_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdncheckfailure',
            old_name='address',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='sdncheckfailure',
            name='city',
            field=models.CharField(default='', max_length=32),
        ),
    ]
