# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-19 20:20
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_auto_20191004_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseContractMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('discount', models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=8, null=True)),
                ('discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Absolute', 'Absolute')], default='Percentage', max_length=255)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='source',
            name='card_type',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('american_express', 'American Express'), ('discover', 'Discover')], max_length=255, null=True),
        ),
    ]
