# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-19 20:34
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_auto_20191119_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisecontractmetadata',
            name='discount',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='card_type',
            field=models.CharField(blank=True, choices=[('mastercard', 'MasterCard'), ('american_express', 'American Express'), ('discover', 'Discover'), ('visa', 'Visa')], max_length=255, null=True),
        ),
    ]
