# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-18 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_card_type_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisecontractmetadata',
            name='discount_value',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
    ]
