# Generated by Django 2.2.15 on 2020-08-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_sdnfallbackmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDNFallbackData',
            fields=[
                ('sdn_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('sdn_type', models.CharField(db_index=True, max_length=255)),
                ('names', models.TextField()),
                ('addresses', models.TextField()),
                ('countries', models.CharField(max_length=255)),
                ('sdn_fallback_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.SDNFallbackMetadata')),
            ],
        ),
    ]
