# Generated by Django 2.2.15 on 2020-08-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_sdnfallbackmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDNFallbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdn_id', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('sdn_type', models.CharField(max_length=255, null=True)),
                ('names', models.TextField()),
                ('addresses', models.TextField(null=True)),
                ('countries', models.CharField(max_length=2, null=True)),
                ('csv_import_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.SDNFallbackMetadata')),
            ],
        ),
    ]
