# Generated by Django 2.2.15 on 2020-09-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_sdnfallbackdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SDNFallbackData',
        ),
    ]
