# Generated by Django 2.2.15 on 2020-09-10 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_delete_sdnfallbackdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDNFallbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, default='', max_length=255)),
                ('sdn_type', models.CharField(db_index=True, default='', max_length=255)),
                ('names', models.TextField(default='')),
                ('addresses', models.TextField(default='')),
                ('countries', models.CharField(default='', max_length=255)),
                ('sdn_fallback_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.SDNFallbackMetadata')),
            ],
        ),
    ]
