# Generated by Django 3.2.12 on 2022-08-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_sdnfallbackdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprocessorresponse',
            name='original_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Original Transaction ID'),
        ),
    ]
