# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-28 20:11
from __future__ import unicode_literals

from django.db import migrations
import ecommerce.extensions.offer.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0017_condition_journal_bundle_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalBundleAbsoluteDiscountBenefit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=(ecommerce.extensions.offer.mixins.BenefitWithoutRangeMixin, ecommerce.extensions.offer.mixins.AbsoluteBenefitMixin, 'offer.absolutediscountbenefit'),
        ),
        migrations.CreateModel(
            name='JournalBundleCondition',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=(ecommerce.extensions.offer.mixins.SingleItemConsumptionConditionMixin, 'offer.condition'),
        ),
        migrations.CreateModel(
            name='JournalBundlePercentageDiscountBenefit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=(ecommerce.extensions.offer.mixins.BenefitWithoutRangeMixin, ecommerce.extensions.offer.mixins.PercentageBenefitMixin, 'offer.percentagediscountbenefit'),
        ),
    ]
