# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-03 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalBundleAbsoluteDiscountBenefit',
        ),
        migrations.DeleteModel(
            name='JournalBundleCondition',
        ),
        migrations.DeleteModel(
            name='JournalBundlePercentageDiscountBenefit',
        ),
    ]
