# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-09 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20190909_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalBundleAbsoluteDiscountBenefit',
        ),
        migrations.DeleteModel(
            name='JournalBundleCondition',
        ),
        migrations.DeleteModel(
            name='JournalBundlePercentageDiscountBenefit',
        ),
    ]
