# Generated by Django 2.2.17 on 2021-07-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IAPProcessorConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retry_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Number of times to retry failing IAP client actions (e.g., payment creation, payment execution)')),
            ],
            options={
                'verbose_name': 'IAP Processor Configuration',
            },
        ),
    ]
