# Generated by Django 3.2.12 on 2022-08-26 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_sdnfallbackdata'),
        ('iap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProcessorResponseExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Original Transaction ID')),
                ('processor_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='payment.paymentprocessorresponse')),
            ],
        ),
    ]
