# Generated by Django 3.2.15 on 2023-06-20 06:38

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0004_create_disbale_mobile_repeat_order_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprocessorresponseextension',
            name='meta_data',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
