# Generated by Django 3.2.19 on 2023-08-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0005_paymentprocessorresponseextension_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='iapprocessorconfiguration',
            name='mobile_team_email',
            field=models.EmailField(default='', max_length=254, verbose_name='mobile team email'),
        ),
    ]
