# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-26 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0011_auto_20170215_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField(help_text='Start date/time for the program discount.')),
                ('end_datetime', models.DateTimeField(help_text='End date/time for the program discount.')),
                ('last_edited_datetime', models.DateTimeField(auto_now=True)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='offer.ConditionalOffer')),
            ],
        ),
    ]
