# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-26 01:38


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_auto_20161025_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='enable_sailthru',
            field=models.BooleanField(default=True, help_text=b'DEPRECATED: Use SiteConfiguration!', verbose_name='Enable Sailthru Reporting'),
        ),
    ]
