# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-06 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_auto_20170525_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstockrecord',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
