# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 11:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_partner_default_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='default_site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
    ]
