# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-15 21:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_historicalpartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpartner',
            name='enable_sailthru',
            field=models.BooleanField(default=True, help_text='DEPRECATED: Use SiteConfiguration!', verbose_name='Enable Sailthru Reporting'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='enable_sailthru',
            field=models.BooleanField(default=True, help_text='DEPRECATED: Use SiteConfiguration!', verbose_name='Enable Sailthru Reporting'),
        ),
    ]
