# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-05 14:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0016_auto_20191115_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpartner',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date Created'),
        ),
    ]
