# Generated by Django 2.2.17 on 2021-05-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0017_auto_20200305_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpartner',
            name='enable_sailthru',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='enable_sailthru',
        ),
    ]
