# Generated by Django 2.2.24 on 2022-05-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0018_remove_partner_enable_sailthru'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstockrecord',
            name='android_sku',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalstockrecord',
            name='ios_sku',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='android_sku',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='ios_sku',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
