# Generated by Django 3.2.20 on 2023-11-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0018_remove_partner_enable_sailthru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstockrecord',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='historicalstockrecord',
            name='price_retail',
        ),
        migrations.RemoveField(
            model_name='stockrecord',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='stockrecord',
            name='price_retail',
        ),
        migrations.AlterField(
            model_name='historicalstockrecord',
            name='price_excl_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price'),
        ),
        migrations.RenameField(
            model_name='historicalstockrecord',
            old_name='price_excl_tax',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='price_excl_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price'),
        ),
        migrations.RenameField(
            model_name='stockrecord',
            old_name='price_excl_tax',
            new_name='price',
        ),
    ]
