# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 05:01
from __future__ import unicode_literals

from django.db import migrations

from ecommerce.extensions.basket.constants import REPEAT_PURCHASE_SWITCH_NAME


def create_switch(apps, schema_editor):
    """Create and activate the sailthru_enable switch if it does not already exist."""
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.get_or_create(name=REPEAT_PURCHASE_SWITCH_NAME, defaults={'active': True})


def delete_switch(apps, schema_editor):
    """Delete the sailthru_enable switch."""
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.filter(name=REPEAT_PURCHASE_SWITCH_NAME).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('waffle', '0001_initial'),
        ('basket', '0009_auto_20170215_2229'),
    ]

    operations = [
        migrations.RunPython(create_switch, reverse_code=delete_switch),
    ]
