# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-05 14:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0012_add_purchaser_basket_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date Created'),
        ),
    ]
