# Generated by Django 3.2.20 on 2024-02-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0017_alter_lineattribute_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='tax_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='VAT rate code'),
        ),
    ]
