# Generated by Django 2.2.26 on 2022-02-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLearnerAssessmentDataTranslationAuditDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_abc_def', models.PositiveIntegerField(db_index=True)),
            ],
        ),
    ]
