# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-05 14:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20191115_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
