# Generated by Django 3.2.20 on 2023-11-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20211213_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productalert',
            options={'ordering': ['-date_created'], 'verbose_name': 'Product alert', 'verbose_name_plural': 'Product alerts'},
        ),
        migrations.AlterField(
            model_name='productalert',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created'),
        ),
    ]
