# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-16 04:24


import oscar.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_auto_20170215_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='proxy_class',
            field=oscar.models.fields.NullCharField(default=None, max_length=255, verbose_name='Custom class'),
        ),
    ]
