# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-22 21:11
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_auto_20170215_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseCustomerUserLinkBenefit',
            fields=[
                ('benefit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offer.Benefit')),
                ('enterprise_customer_uuid', models.UUIDField(help_text='UUID for an EnterpriseCustomer from the Enterprise Service.')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
            },
            bases=('offer.benefit',),
        ),
    ]
