# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-25 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_auto_20170215_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='program_uuid',
            field=models.UUIDField(blank=True, help_text='UUID of the program stored in the Course Catalog service.', null=True),
        ),
    ]
