# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-12 13:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_condition_program_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseCustomerUserAbsoluteDiscountBenefit',
            fields=[
                ('benefit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offer.Benefit')),
                ('enterprise_customer_uuid', models.UUIDField()),
            ],
            options={
                'verbose_name': 'Absolute enterprise entitlement discount benefit',
                'verbose_name_plural': 'Absolute enterprise entitlement discount benefits',
            },
            bases=('offer.absolutediscountbenefit',),
        ),
        migrations.CreateModel(
            name='EnterpriseCustomerUserPercentageBenefit',
            fields=[
                ('benefit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offer.Benefit')),
                ('enterprise_customer_uuid', models.UUIDField()),
            ],
            options={
                'verbose_name': 'Percentage enterprise entitlement discount benefit',
                'verbose_name_plural': 'Percentage enterprise entitlement discount benefits',
            },
            bases=('offer.percentagediscountbenefit',),
        ),
        migrations.CreateModel(
            name='DataSharingConsentCondition',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('offer.condition',),
        ),
    ]
