# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-12 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_condition_program_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='program_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
