# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 07:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_condition_program_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='course_catalog',
            field=models.PositiveIntegerField(blank=True, help_text='Course Catalog ID from the Discovery Service.', null=True),
        ),
    ]
