# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0016_auto_20180124_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='digital_book_bundle',
            field=models.UUIDField(blank=True, null=True, verbose_name='DigitalBookBundle UUID'),
        ),
    ]
