# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0017_condition_digital_book_bundle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='digital_book_bundle',
            new_name='digital_book_bundle_uuid',
        ),
    ]
