# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 16:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0020_migrate_partner_to_coupon_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='enterprise_customer_catalog',
            field=models.UUIDField(blank=True, help_text='UUID for an EnterpriseCustomerCatalog from the Enterprise Service.', null=True),
        ),
    ]
