# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-10 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0024_add_history_models_de_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='journal_bundle_uuid',
        ),
        migrations.RemoveField(
            model_name='historicalcondition',
            name='journal_bundle_uuid',
        ),
    ]
