# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-13 17:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0026_auto_20190903_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionaloffer',
            name='exclusive',
            field=models.BooleanField(default=True, help_text='Exclusive offers cannot be combined on the same items', verbose_name='Exclusive offer'),
        ),
        migrations.AddField(
            model_name='historicalconditionaloffer',
            name='exclusive',
            field=models.BooleanField(default=True, help_text='Exclusive offers cannot be combined on the same items', verbose_name='Exclusive offer'),
        ),
    ]
