# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-26 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_auto_20191126_1806'),
        ('offer', '0028_auto_20191115_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionaloffer',
            name='enterprise_contract_metadata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.EnterpriseContractMetadata'),
        ),
        migrations.AddField(
            model_name='historicalconditionaloffer',
            name='enterprise_contract_metadata',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payment.EnterpriseContractMetadata'),
        ),
    ]
