# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-11 10:58


from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0029_auto_20191126_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferAssignmentEmailTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('enterprise_customer', models.UUIDField(help_text='UUID for an EnterpriseCustomer from the Enterprise Service.')),
                ('email_type', models.CharField(choices=[('assign', 'Assign'), ('remind', 'Remind'), ('revoke', 'Revoke')], default='assign', max_length=32)),
                ('email_greeting', models.CharField(max_length=300)),
                ('email_closing', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True, help_text='Make a particular template version active.')),
            ],
            options={
                'ordering': ('enterprise_customer', '-active'),
            },
        ),
        migrations.AddIndex(
            model_name='offerassignmentemailtemplates',
            index=models.Index(fields=['enterprise_customer', 'email_type'], name='offer_offer_enterpr_a9dd7f_idx'),
        ),
    ]
