# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-24 07:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0030_offerassignmentemailtemplates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerassignmentemailtemplates',
            name='email_closing',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='offerassignmentemailtemplates',
            name='email_greeting',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='offerassignmentemailtemplates',
            name='email_type',
            field=models.CharField(choices=[('assign', 'Assign'), ('remind', 'Remind'), ('revoke', 'Revoke')], max_length=32),
        ),
    ]
