# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-05 11:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0031_auto_20200224_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionaloffer',
            name='sales_force_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalconditionaloffer',
            name='sales_force_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
