# Generated by Django 2.2.12 on 2020-04-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0034_auto_20200403_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerassignmentemailtemplates',
            name='name',
            field=models.CharField(default='Template', max_length=255),
        ),
    ]
