# Generated by Django 2.2.12 on 2020-05-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0035_offerassignmentemailtemplates_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionaloffer',
            name='max_user_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='When an offer has given more discount than this threshold to orders of a user, then the offer becomes unavailable for that user', max_digits=12, null=True, verbose_name='Max user discount'),
        ),
        migrations.AddField(
            model_name='historicalconditionaloffer',
            name='max_user_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='When an offer has given more discount than this threshold to orders of a user, then the offer becomes unavailable for that user', max_digits=12, null=True, verbose_name='Max user discount'),
        ),
    ]
