# Generated by Django 2.2.12 on 2020-05-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0036_auto_20200514_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerassignmentemailtemplates',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
