# Generated by Django 2.2.12 on 2020-06-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0037_auto_20200528_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerassignment',
            options={},
        ),
        migrations.AlterField(
            model_name='historicalofferassignment',
            name='code',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='historicalofferassignment',
            name='status',
            field=models.CharField(choices=[('EMAIL_PENDING', 'Email to user pending.'), ('ASSIGNED', 'Code successfully assigned to user.'), ('REDEEMED', 'Code has been redeemed by user.'), ('EMAIL_BOUNCED', 'Email to user bounced.'), ('REVOKED', 'Code has been revoked for this user.')], db_index=True, default='EMAIL_PENDING', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalofferassignment',
            name='user_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='offerassignment',
            name='code',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='offerassignment',
            name='status',
            field=models.CharField(choices=[('EMAIL_PENDING', 'Email to user pending.'), ('ASSIGNED', 'Code successfully assigned to user.'), ('REDEEMED', 'Code has been redeemed by user.'), ('EMAIL_BOUNCED', 'Email to user bounced.'), ('REVOKED', 'Code has been revoked for this user.')], db_index=True, default='EMAIL_PENDING', max_length=255),
        ),
        migrations.AlterField(
            model_name='offerassignment',
            name='user_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddIndex(
            model_name='offerassignment',
            index=models.Index(fields=['code', 'user_email'], name='offer_offer_code_70b216_idx'),
        ),
        migrations.AddIndex(
            model_name='offerassignment',
            index=models.Index(fields=['code', 'status'], name='offer_offer_code_4aa171_idx'),
        ),
    ]
