# Generated by Django 2.2.12 on 2020-06-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0038_auto_20200605_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historicalcondition',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical condition'},
        ),
        migrations.AlterField(
            model_name='condition',
            name='enterprise_customer_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='EnterpriseCustomer UUID'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='program_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Program UUID'),
        ),
        migrations.AlterField(
            model_name='historicalcondition',
            name='enterprise_customer_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='EnterpriseCustomer UUID'),
        ),
        migrations.AlterField(
            model_name='historicalcondition',
            name='program_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Program UUID'),
        ),
        migrations.AddIndex(
            model_name='condition',
            index=models.Index(fields=['enterprise_customer_uuid', 'program_uuid'], name='offer_condi_enterpr_611782_idx'),
        ),
    ]
