# Generated by Django 2.2.12 on 2020-06-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0039_auto_20200617_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalofferassignment',
            name='assignment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Offer Assignment Date'),
        ),
        migrations.AddField(
            model_name='historicalofferassignment',
            name='last_reminder_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Reminder Date'),
        ),
        migrations.AddField(
            model_name='historicalofferassignment',
            name='revocation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Offer Revocation Date'),
        ),
        migrations.AddField(
            model_name='offerassignment',
            name='assignment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Offer Assignment Date'),
        ),
        migrations.AddField(
            model_name='offerassignment',
            name='last_reminder_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Reminder Date'),
        ),
        migrations.AddField(
            model_name='offerassignment',
            name='revocation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Offer Revocation Date'),
        ),
    ]
