# Generated by Django 2.2.13 on 2020-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0040_auto_20200619_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionaloffer',
            name='emails_for_usage_alert',
            field=models.TextField(blank=True, help_text='Comma separated emails which will receive the offer usage alerts', verbose_name='Emails to receive offer usage alert'),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='usage_email_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=8),
        ),
        migrations.AddField(
            model_name='historicalconditionaloffer',
            name='emails_for_usage_alert',
            field=models.TextField(blank=True, help_text='Comma separated emails which will receive the offer usage alerts', verbose_name='Emails to receive offer usage alert'),
        ),
        migrations.AddField(
            model_name='historicalconditionaloffer',
            name='usage_email_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=8),
        ),
    ]
