# Generated by Django 2.2.14 on 2020-07-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0041_auto_20200707_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerassignmentemailtemplates',
            name='email_subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
