# Generated by Django 2.2.14 on 2020-07-29 07:41

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0042_offerassignmentemailtemplates_email_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferUsageEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('offer_email_metadata', jsonfield.fields.JSONField(default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={})),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.ConditionalOffer')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
