# Generated by Django 2.2.16 on 2020-09-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0043_offerusageemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionaloffer',
            name='name',
            field=models.CharField(help_text="This is displayed within the customer's basket", max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalconditionaloffer',
            name='name',
            field=models.CharField(help_text="This is displayed within the customer's basket", max_length=128, verbose_name='Name'),
        ),
    ]
