# Generated by Django 2.2.16 on 2020-10-16 07:55

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0043_offerusageemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAssignmentNudgeEmailTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('email_greeting', models.TextField(blank=True, null=True)),
                ('email_closing', models.TextField(blank=True, null=True)),
                ('email_subject', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, help_text='Make a particular template version active.')),
                ('name', models.CharField(max_length=255)),
                ('email_type', models.CharField(choices=[('Day3', 'Day 3'), ('Day10', 'Day 10'), ('Day19', 'Day 19')], max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
