# Generated by Django 2.2.16 on 2020-10-21 09:20

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0044_codeassignmentnudgeemailtemplates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAssignmentNudgeEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(db_index=True, max_length=128)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('email_date', models.DateTimeField()),
                ('already_sent', models.BooleanField(default=False, help_text='Email has been sent.')),
                ('is_subscribed', models.BooleanField(default=True, help_text='This user should receive email')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.CodeAssignmentNudgeEmailTemplates')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
