# Generated by Django 2.2.17 on 2021-03-12 14:25

from django.db import migrations
import ecommerce.extensions.offer.models
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0048_auto_20201112_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeassignmentnudgeemails',
            name='options',
            field=jsonfield.fields.JSONField(default=ecommerce.extensions.offer.models.CodeAssignmentNudgeEmails.options_default, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}),
        ),
    ]
