# Generated by Django 2.2.23 on 2021-08-27 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0049_codeassignmentnudgeemails_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateFileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('size', models.PositiveIntegerField()),
                ('url', models.URLField(max_length=300)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_files', to='offer.OfferAssignmentEmailTemplates')),
            ],
        ),
    ]
