# Generated by Django 3.2.15 on 2022-09-30 17:59

from django.db import migrations
import ecommerce.extensions.offer.models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0051_offerusageemail_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeassignmentnudgeemails',
            name='options',
            field=jsonfield.fields.JSONField(default=ecommerce.extensions.offer.models.CodeAssignmentNudgeEmails.options_default),
        ),
        migrations.AlterField(
            model_name='offerusageemail',
            name='offer_email_metadata',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
