# Generated by Django 3.2.18 on 2023-06-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0052_jsonfield_codeassignmentnudgeemails_offerusageemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionaloffer',
            name='salesforce_opportunity_line_item',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalconditionaloffer',
            name='salesforce_opportunity_line_item',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
