# Generated by Django 3.2.18 on 2023-06-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0053_auto_20230601_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionaloffer',
            name='sales_force_id',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalconditionaloffer',
            name='sales_force_id',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
