# Generated by Django 3.2.25 on 2024-05-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0055_auto_20231108_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedUnitDiscountBenefit',
            fields=[
            ],
            options={
                'verbose_name': 'Fixed unit discount benefit',
                'verbose_name_plural': 'Fixed unit discount benefits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.absolutediscountbenefit',),
        ),
        migrations.AddField(
            model_name='rangeproductfileupload',
            name='upload_type',
            field=models.CharField(choices=[('included', 'Included products upload'), ('excluded', 'Excluded products upload')], default='included', max_length=8),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='type',
            field=models.CharField(blank=True, choices=[('Percentage', "Discount is a percentage off of the product's value"), ('Absolute', "Discount is a fixed amount off of the basket's total"), ('Fixed', "Discount is a fixed amount off of the product's value"), ('Multibuy', 'Discount is to give the cheapest product for free'), ('Fixed price', 'Get the products that meet the condition for a fixed price'), ('Shipping absolute', 'Discount is a fixed amount of the shipping cost'), ('Shipping fixed price', 'Get shipping for a fixed price'), ('Shipping percentage', 'Discount is a percentage off of the shipping cost')], max_length=128, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicalbenefit',
            name='type',
            field=models.CharField(blank=True, choices=[('Percentage', "Discount is a percentage off of the product's value"), ('Absolute', "Discount is a fixed amount off of the basket's total"), ('Fixed', "Discount is a fixed amount off of the product's value"), ('Multibuy', 'Discount is to give the cheapest product for free'), ('Fixed price', 'Get the products that meet the condition for a fixed price'), ('Shipping absolute', 'Discount is a fixed amount of the shipping cost'), ('Shipping fixed price', 'Get shipping for a fixed price'), ('Shipping percentage', 'Discount is a percentage off of the shipping cost')], max_length=128, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicalrange',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='range',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
