# Generated by Django 3.2.22 on 2023-12-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0055_auto_20231108_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangeproductfileupload',
            name='upload_type',
            field=models.CharField(choices=[('included', 'Included products upload'), ('excluded', 'Excluded products upload')], default='included', max_length=8),
        ),
        migrations.AlterField(
            model_name='historicalrange',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='range',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
